import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => {
    localStorage.clear()
    const date = new Date().toISOString().slice(0, 10)
    localStorage.setItem('balance.appState.v1', JSON.stringify({
      schemaVersion: 1, deviceId: 'scroll-test', localSequence: 0, historyRevision: 0,
      activePlanDate: date, templates: [], goals: [], goalCompletions: [], operations: [],
      plans: [{ id: 'scroll-plan', date, dailyReminder: '', items: Array.from({ length: 100 }, (_, i) => ({
        id: `task-${i}`, text: `Synthetic task ${i}`, html: `Synthetic task ${i}`,
        children: [], done: false, startMinutes: null, endMinutes: null,
      })) }],
    }))
  })
  await page.reload()
})

test('Escape leaves task editing; held W/S accelerates linearly and stops immediately', async ({ page }) => {
  const editor = page.locator('[data-plan-text-input]').first()
  await editor.focus()
  await page.keyboard.press('Escape')
  await expect(editor).not.toBeFocused()
  const scrollTop = () => page.locator('.workspace').evaluate(el => el.scrollTop)
  await page.clock.install()
  await page.clock.pauseAt(new Date())
  const initial = await scrollTop()
  await page.keyboard.down('s')
  await page.clock.runFor(400)
  const first = await scrollTop()
  await page.clock.runFor(400)
  const second = await scrollTop()
  // At 950 px/s with a linear 100% ramp over 1000 ms, the first and second
  // 400 ms intervals cover 456 px and 608 px respectively.
  expect(first - initial).toBeGreaterThan(446)
  expect(first - initial).toBeLessThan(466)
  expect(second - first).toBeGreaterThan(598)
  expect(second - first).toBeLessThan(618)
  await page.clock.runFor(400)
  const third = await scrollTop()
  // The ramp completes during this interval and reaches 1900 px/s.
  expect(third - second).toBeGreaterThan(731)
  expect(third - second).toBeLessThan(751)
  await page.keyboard.up('s')
  await page.clock.runFor(500)
  expect(await scrollTop()).toBe(third)
  await page.keyboard.down('w')
  await page.clock.runFor(500)
  await page.keyboard.up('w')
  expect(third - await scrollTop()).toBeGreaterThan(575)
  await editor.focus()
  const beforeTyping = await scrollTop()
  await page.keyboard.down('s')
  await page.clock.runFor(500)
  await page.keyboard.up('s')
  expect(await scrollTop()).toBe(beforeTyping)
  await expect(editor).toContainText('s')
  await page.keyboard.press('Escape')
  await page.keyboard.down('s')
  await page.clock.runFor(100)
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  const afterBlur = await scrollTop()
  await page.clock.runFor(500)
  expect(await scrollTop()).toBe(afterBlur)
  await page.keyboard.up('s')
})

test('admin settings show defaults, persist scroll tuning and reset it; studio moved out of Settings', async ({ page }) => {
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page.getByLabel('Iridescent background controls')).toHaveCount(0)
  await page.getByRole('button', { name: 'Admin Settings', exact: true }).click()
  await expect(page.getByText('Default: 950 px/s.', { exact: false })).toBeVisible()
  const speed = page.getByLabel('Scroll speed (px/s)')
  const acceleration = page.getByLabel('Acceleration duration (ms)')
  const increase = page.getByLabel('Maximum speed increase (%)')
  await expect(speed).toHaveValue('950')
  await expect(acceleration).toHaveValue('1000')
  await expect(increase).toHaveValue('100')
  await speed.fill('1200')
  await speed.press('Tab')
  await acceleration.fill('1600')
  await acceleration.press('Tab')
  await increase.fill('75')
  await increase.press('Tab')
  await page.reload()
  await page.getByRole('button', { name: 'Admin Settings', exact: true }).click()
  await expect(speed).toHaveValue('1200')
  await expect(acceleration).toHaveValue('1600')
  await expect(increase).toHaveValue('75')
  await expect(page.getByLabel('Iridescent background controls')).toBeVisible()
  await page.getByRole('button', { name: 'Today', exact: true }).click()
  await page.clock.install()
  await page.clock.pauseAt(new Date())
  const workspace = page.locator('.workspace')
  const initial = await workspace.evaluate(el => el.scrollTop)
  await page.keyboard.down('s')
  await page.clock.runFor(400)
  await page.keyboard.up('s')
  const customizedDistance = await workspace.evaluate(el => el.scrollTop) - initial
  expect(customizedDistance).toBeGreaterThan(515)
  expect(customizedDistance).toBeLessThan(535)
  await page.getByRole('button', { name: 'Admin Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Reset scroll speed' }).click()
  await page.getByRole('button', { name: 'Reset acceleration duration' }).click()
  await page.getByRole('button', { name: 'Reset speed increase' }).click()
  await expect(speed).toHaveValue('950')
  await expect(acceleration).toHaveValue('1000')
  await expect(increase).toHaveValue('100')
})
